### ISSUE TITLE
Final upgrade to `ape-core` v0.9.0

### ISSUE THREAD

**Issue by aschung01** [weavel-ai/Ape#38]
## Todos
- [x] Rename `Evaluate` to `Evaluator` (Base classes and file, directory names too)
- [x] Rename `Generate` to `Generator` (Base classes and file, directory names too)
- [x] Set `ape-common` version to `0.2.0`, `ape-core` version to `0.9.0`

**Comment by aschung01** [comment]
PR #36
